[2025-07-14T02:26:18.993+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Load_artist_dim_table manual__2025-07-14T02:25:31.239507+00:00 [queued]>
[2025-07-14T02:26:19.011+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Load_artist_dim_table manual__2025-07-14T02:25:31.239507+00:00 [queued]>
[2025-07-14T02:26:19.012+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-07-14T02:26:19.035+0000] {taskinstance.py:1350} INFO - Executing <Task(LoadDimensionOperator): Load_artist_dim_table> on 2025-07-14 02:25:31.239507+00:00
[2025-07-14T02:26:19.047+0000] {standard_task_runner.py:57} INFO - Started process 584 to run task
[2025-07-14T02:26:19.053+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Load_artist_dim_table', 'manual__2025-07-14T02:25:31.239507+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpxv548p85']
[2025-07-14T02:26:19.058+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask Load_artist_dim_table
[2025-07-14T02:26:19.155+0000] {task_command.py:410} INFO - Running <TaskInstance: final_project.Load_artist_dim_table manual__2025-07-14T02:25:31.239507+00:00 [running]> on host d7ac0fd04b06
[2025-07-14T02:26:19.288+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Load_artist_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-14T02:25:31.239507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-14T02:25:31.239507+00:00'
[2025-07-14T02:26:19.305+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:26:20.602+0000] {sql.py:375} INFO - Running statement: INSERT INTO artist_table 
        SELECT distinct artist_id, artist_name, artist_location, artist_latitude, artist_longitude
        FROM staging_songs
    ;, parameters: None
[2025-07-14T02:26:20.958+0000] {load_dimension.py:35} ERROR - 'artist_table' へのデータのロード中にエラーが発生しました: relation "artist_table" does not exist

[2025-07-14T02:26:20.960+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/load_dimension.py", line 33, in execute
    redshift.run(exec_sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "artist_table" does not exist

[2025-07-14T02:26:20.983+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=final_project, task_id=Load_artist_dim_table, execution_date=20250714T022531, start_date=20250714T022618, end_date=20250714T022620
[2025-07-14T02:26:20.998+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 30 for task Load_artist_dim_table (relation "artist_table" does not exist
; 584)
[2025-07-14T02:26:21.022+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-07-14T02:26:21.081+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
